### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mlafeldt** [chaos-eng/chaos-eng.github.io#2]
Hi,

I'd like to know if the text published at http://principlesofchaos.org/ is licensed in any way? Is it fine to copy and use it freely?

Thanks for the great document, by the way.

**Comment by mlafeldt** [comment]
@clr @lorin Could you please have a look?

**Comment by lorin** [comment]
@mlafeldt License added: copy and use away!

**Comment by mlafeldt** [comment]
Thank you, Lorin!
