### ISSUE TITLE
Consider removing "distributed" from the intro definition?

### ISSUE THREAD

**Issue by russmiles** [chaos-eng/chaos-eng.github.io#22]
Although many systems are distributed, I've found many that wouldn't _typically_ be labelled as such and so I'd like to propose removing that from the short introduction definition to the principles.

**Comment by lorin** [comment]
Seems reasonable to me. If there are no objections, I'll merge the submitted PR.

**Comment by russmiles** [comment]
No objections here :) Thanks @lorin!

**Comment by lorin** [comment]
Done!
