### ISSUE TITLE
Using Markdown and Static Site Generators

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [chaos-eng/chaos-eng.github.io#27]
I believe maintaining an HTML document is hard, and I want to help you to use markdown files. Do you consider that?

Also, I want to thank you for the document :smiley:

**Comment by lorin** [comment]
I'm open to the idea of a site generator. I don't have the time to migrate from html to a static site generator, but I'd consider a PR that implemented it, as long as it supported all of the language translations.

**Comment by lorin** [comment]
This is now done, thanks to @DenisBalan !
