### ISSUE TITLE
I can't join the chaos-community

### ISSUE THREAD

**Issue by petrewoo** [chaos-eng/chaos-eng.github.io#33]
When i click hyperlink about Chaos Community, I occurred error below:
`You do not have permission to access this content. (#418)`
and there is not a `join request` button any where, help

**Comment by lorin** [comment]
I made some adjustments to the permissions, you should be able to join the group now by following the link. Can you confirm whether or not it's now working for you?

**Comment by petrewoo** [comment]
Sorry for the late reply.
It works for me, thank you very much.
