### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by kittsville** [chaos-eng/chaos-eng.github.io#41]
Please modify the GitHub Pages config to enforce HTTPS. HTTPS everywhere is recommended for basic web security:

https://github.com/chaos-eng/chaos-eng.github.io/settings

![image](https://user-images.githubusercontent.com/6013087/89042314-9cc7e300-d33e-11ea-99b9-2685cf63190e.png)

**Comment by lorin** [comment]
Done
