### ISSUE TITLE
What is a good way to discuss and submit corrections to a translation?

### ISSUE THREAD

**Issue by epogrebnyak** [chaos-eng/chaos-eng.github.io#43]
- In Russian I think "в стадии эксплуатации" is close to original "in production", than "в эксплуатационной среде". 
- why "вопрос ребром" - there is no duality in original text, "on the heels" - it means quick succession, immediate follow-up
- several punctuation mistakes, and so forth

Should I make a PR or try find who made the original translation?

**Comment by lorin** [comment]
Feel free to go ahead and submit a PR to improve the translation.

**Comment by lorin** [comment]
Merged the PR.

**Comment by lorin** [comment]
Fixed by #53.

**Comment by epogrebnyak** [comment]
Thanks for merging!
