### ISSUE TITLE
Should **Last Update** date be updated?

### ISSUE THREAD

**Issue by setheliot** [chaos-eng/chaos-eng.github.io#44]
Content says **Last Update: 2018 May**

I noted that "distributed system" was simplified to just "system" in the definition.  I investigated to see when/why this was done and found PR https://github.com/chaos-eng/chaos-eng.github.io/pull/23 which is from Mar 2019.

Is this too minor a change to require an update to the **Last Update** date, or should **Last Update** be updated?
(That last sentence sounds like a tongue-twister... :-) )

**Comment by lorin** [comment]
Sounds reasonable to update the date. Can you open a PR for this?

**Comment by setheliot** [comment]
https://github.com/chaos-eng/chaos-eng.github.io/pull/47

I note that the hugo file gen on my machine changed `&rsquo;` to `'` -- it renders fine on my machine.., let me know if this is a problem and any advice on how to fix

**Comment by setheliot** [comment]
also @lorin can you share why "distributed" was removed?

**Comment by setheliot** [comment]
@lorin , my pull request is still waiting... can you please pull it?

https://github.com/chaos-eng/chaos-eng.github.io/pull/47

**Comment by lorin** [comment]
Done!
