### ISSUE TITLE
German version

### ISSUE THREAD

**Issue by Schumburg** [chaos-eng/chaos-eng.github.io#46]
I miss a German version. Are you interesterd to get one? Or is somebody working on it?

**Comment by patrickmatula** [comment]
I miss a German version too. I don't see any pull request. Because of that, I would guess nobody is working on that.

**Comment by lorin** [comment]
@Schumburg I'm not aware of anybody working on a German version. Please go ahead and submit as a PR if you're interested.

**Comment by jerptrs** [comment]
Just Deepl it?xd

**Comment by lorin** [comment]
Fixed by #54.
