### ISSUE TITLE
Website is unavailable (404)

### ISSUE THREAD

**Issue by Devatoria** [chaos-eng/chaos-eng.github.io#52]
The http://principlesofchaos.org/ URL specified in the readme and at some other places now leads to a 404 Github page.

**Comment by lorin** [comment]
I think I fixed this. Please re-open if it happens again.

**Comment by aymericDD** [comment]
The issue is still alive 😢

**Comment by lorin** [comment]
@aymericDD Can you verify that you are still seeing issues? I see the page loading at http://principlesofchaos.org/

**Comment by aymericDD** [comment]
Yes! The issue is fixed 👍
